// <auto-generated />
using System;
using BlazorRPUA.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorRPUA.Server.Migrations
{
    [DbContext(typeof(EFDB))]
    [Migration("20200916182334_prva")]
    partial class prva
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlazorRPUA.Shared.Adresa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Broj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drzava")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosBroj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ulica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Adresas");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Broj = "13",
                            Drzava = "Srbija",
                            Grad = "Novi Pazar",
                            PosBroj = "36300",
                            Ulica = "Mehmeda Alibašića"
                        },
                        new
                        {
                            ID = 2,
                            Broj = "BB",
                            Drzava = "Srbija",
                            Grad = "Novi Pazar",
                            PosBroj = "36300",
                            Ulica = "Kragujevačka"
                        });
                });

            modelBuilder.Entity("BlazorRPUA.Shared.PrimalacUsluga", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdresaID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KontaktTel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AdresaID");

                    b.ToTable("PrimalacUslugas");
                });

            modelBuilder.Entity("BlazorRPUA.Shared.PrimalacUsluga", b =>
                {
                    b.HasOne("BlazorRPUA.Shared.Adresa", "Adresa")
                        .WithMany()
                        .HasForeignKey("AdresaID");
                });
#pragma warning restore 612, 618
        }
    }
}
