// <auto-generated />
using System;
using BlazorRPUA.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorRPUA.Server.Migrations
{
    [DbContext(typeof(EFDB))]
    [Migration("20200928182024_inicijalna")]
    partial class inicijalna
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlazorRPUA.Shared.Adresa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Broj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drzava")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosBroj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ulica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Adresas");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Broj = "13",
                            Drzava = "Srbija",
                            Grad = "Novi Pazar",
                            PosBroj = "36300",
                            Ulica = "Mehmeda Alibašića"
                        },
                        new
                        {
                            ID = 2,
                            Broj = "BB",
                            Drzava = "Srbija",
                            Grad = "Novi Pazar",
                            PosBroj = "36300",
                            Ulica = "Kragujevačka"
                        });
                });

            modelBuilder.Entity("BlazorRPUA.Shared.PrimalacUsluga", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdresaID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KontaktTel")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AdresaID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("KontaktTel")
                        .IsUnique()
                        .HasFilter("[KontaktTel] IS NOT NULL");

                    b.ToTable("PrimalacUslugas");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "esad@dr.com",
                            Ime = "Esad",
                            KontaktTel = "063614616",
                            Prezime = "Međedović"
                        });
                });

            modelBuilder.Entity("BlazorRPUA.Shared.PrimalacUsluga", b =>
                {
                    b.HasOne("BlazorRPUA.Shared.Adresa", "Adresa")
                        .WithMany()
                        .HasForeignKey("AdresaID");
                });
#pragma warning restore 612, 618
        }
    }
}
